#+title: Readme
#+subtitle: GPTVA Notes
#+author: Alberto Valdez
#+SETUPFILE: ./config/org-theme-alt.config
#+SETUPFILE: ./config/org-header.config

* GPT Voice Assistant Notes
:PROPERTIES:
:CUSTOM_ID: gpt-voice-assistant-notes
:END:

This repository contains notes for a Python program for using GPT from OpenAI as a voice assistant.

** Plan
:PROPERTIES:
:CUSTOM_ID: plan
:END:

The plan is to create 5 different articles that tackle different sections of the program by functionality.

1. Part 1 - Audio Channel
2. Part 2 - AI Models and Services
3. Part 3 - Web Server and Storage
4. Part 4 - Flow and Conclusion

Part 1 will contain audio theory and practice for audio device, torchaudio, toml config file and audio calibration.

Part 2 will contain constructing classes for loading up local AI models, as well as connecting to remote AI services, plus loading SSML and a YAML file.

Part 3 will contain a simple SQL database, threading and a web socket server for serving HTML and updating messages in real time.

Part 4 will refine the application flow, setup commands, add extra functionality and suggest possible future improvements.
